stages:
  - test
  - build
  - deploy

variables:
  WEBCRAWLER_LATEST_IMAGE: $DOCKER_USER/webcrawler-matricula


##############################################################################
#                                 Test stage                                 #
##############################################################################

test flake8:
  image: ejplatform/python:alpine
  stage: test
  script:
    - flake8

services:
  - mongo:latest

unit test:
  image: python:3.6
  stage: test
  variables:
    DB_URI: 'mongodb://mongo/ru'
  before_script:
    - pip install -r requirements.txt
    - apt-get update
    - apt-get upgrade -y
    - apt-get install default-jdk -y
    - apt-get update && apt-get -y install poppler-utils
    - cd crawler
  script:
    - pytest
  only:
    - /master/


##############################################################################
#                                 Build stage                                #
##############################################################################

build webcrawler:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t $WEBCRAWLER_LATEST_IMAGE .
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker push $WEBCRAWLER_LATEST_IMAGE
  only:
    - /master/
    - /ciHomolog/
  environment: production

build webcrawler-homolog:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t $WEBCRAWLER_LATEST_IMAGE:homolog .
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker push $WEBCRAWLER_LATEST_IMAGE:homolog
  only:
    - /devel/


##############################################################################
#                                 Deploy stage                               #
##############################################################################

deploy_production:
  image: cdrx/rancher-gitlab-deploy
  stage: deploy
  script:
    - "upgrade
            --service webcrawler-matricula
            --environment $RANCHER_ENVIRONMENT
            --stack $RANCHER_STACK
            --rancher-key $RANCHER_ACCESS_KEY
            --rancher-secret $RANCHER_SECRET_KEY
            --rancher-url $RANCHER_URL"
  only:
    - /master/
    - /ciHomolog/

deploy_homolog:
  image: cdrx/rancher-gitlab-deploy
  stage: deploy
  script:
        - "upgrade
            --rancher-url $RANCHER_HOMOLOG_URL
            --rancher-key $RANCHER_HOMOLOG_ACCESS_KEY
            --rancher-secret $RANCHER_HOMOLOG_SECRET_KEY
            --environment $RANCHER_ENVIRONMENT
            --stack $RANCHER_STACK
            --service webcrawler-matricula"
  only:
    - /devel/
